### ISSUE TITLE
Member not exported..

### ISSUE THREAD

**Issue by pbonadero1** [runette/ngx-leaflet-sidebar#1]
I'm getting an issue after install the ngx-leaflet-sidebar...any idea? thanks

<img width="733" alt="Screenshot 2020-01-27 at 17 26 38" src="https://user-images.githubusercontent.com/50961973/73193082-504ee100-412a-11ea-9599-ae25a52dae12.png">

**Comment by runette** [comment]
I am curious about how you got to that point. Why not just install using the npm installer? Since what you have shown is only approximately my code and is not really going to work!

However, I think that you are missing the following compiler directive from the first line 

```ts
/// <reference types='leaflet-sidebar-v2' />
```
You can also import SidebarOptions directly and not through Control. This was a recent change to index.d.ts and requires the latest version of the leaflet-sidebar-v2 npm.

if you want to know more - you read about it on the following posts

https://medium.com/runic-software/quick-guide-to-leaflet-controls-in-angular-io-1b35d0807bdb

https://medium.com/runic-software/advanced-interactive-maps-in-angular-with-leaflet-68baafa03f72

https://runette.gitbook.io/alcm/

**Comment by pbonadero1** [comment]
Thank you Paul!
